### ISSUE TITLE
Print-Job Timeout

### ISSUE THREAD

**Issue by wkuss** [ctalkington/python-ipp#596]
In pyipp's serializer.py, the encode_dict function does not handle the data attribute in data, resulting in file data not being sent to the Print device at print-job.

pyipp version: 0.16.0

**Comment by so-saf** [comment]
@wkuss hi, I ran into a similar problem, my solution was to add the following three lines right to the end of the `encode_dict` function:

```python
if isinstance(data.get("data"), bytes):
    encoded += data['data']
    encoded += struct.pack(">b", IppTag.END.value)
```

ipptool generates the contents of http packets similarly.
This is probably not the best solution, so I would wait for the author's comments.

**Comment by so-saf** [comment]
In general, as it turned out, there are lines of code necessary for printing in the [source files](https://github.com/ctalkington/python-ipp/blob/master/src/pyipp/serializer.py), the functionality was added as part of PR [#510](https://github.com/ctalkington/python-ipp/pull/510), however, I did not find them in the release or tag files

**Comment by wkuss** [comment]
Yeah, that's how I worked it out.
